#!/usr/bin/env bash
# Initialize counter
counter=1

# Loop while counter is less than or equal to 20
while [ $counter -le 20 ]
do
    # Check conditions for different iterations using a case statement
    case $counter in
        4)
            echo "$counter bad luck from China"
            ;;
        9)
            echo "$counter bad luck from Japan"
            ;;
        17)
            echo "$counter bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    
    # Increment counter
    ((counter++))
done

