#!/usr/bin/env bash
# Initialize variables
hour=0
minute=1

# Loop to display time for 12 hours and 59 minutes
while [ $hour -le 12 ]
do
    while [ $minute -le 59 ]
    do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
        if [ $minute -gt 59 ]; then
            ((hour++))
            minute=0
        fi
    done
done | head -n 70

